### ISSUE TITLE
Github Actions deprecating set-output commands

### ISSUE THREAD

**Issue by samleecampspot** [mad9000/actions-find-and-replace-string#6]
Hello!

With the set-output commands being disabled soon, will this package be able to update to use the [Environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files) instead?
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Thanks.

**Comment by samleecampspot** [comment]
I think the fix is to update `@actions/core` to `1.10.0`.

https://github.com/actions/toolkit/pull/1178

**Comment by kishyr** [comment]
Fixed by @mbarouski in #8
